#:schema node_modules/wrangler/config-schema.json
name = "cf-alt-generator"
main = "index.js"
workers_dev = true
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat" ]

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
[ai]
binding = "AI"